name: cicd
on:
  push:

jobs:
  test:
    runs-on: ubuntu-latest
    container: golang:1.27
    steps:
      - uses: actions/checkout@v7
        with:
          fetch-depth: 0
          ref: ${{ github.sha }}

      - name: test
        shell: bash
        run: scripts/test.sh

  build:
    if: github.ref_name == 'main'
    uses: jasondavindev/open-idp/.github/workflows/build.yaml@main
    needs: test
    secrets:
      CONTAINER_REGISTRY: ${{ secrets.CONTAINER_REGISTRY }}
      REGISTRY_PASSWORD: ${{ secrets.REPO_PASSWORD }}
      REGISTRY_USER: ${{ secrets.REPO_USER }}

  deploy:
    needs: build
    uses: jasondavindev/open-idp/.github/workflows/deploy.yaml@main
    with:
      image_tag: ${{ needs.build.outputs.image_tag }}
    permissions:
      contents: write
